Graph library
fynnbrem/brontology pull request #1
Opened 2024-03-15 10:59 UTC by marvinkaldewey

2024-03-26 20:24 UTC, fynnbrem requested changes
Das sieht alles schon sehr sauber aus, allein die DocStrings müssen noch angepasst werden.

Vor allem die Verwendung von Type Annotations ist sehr gut!

2024-03-26 20:24 UTC, fynnbrem commented on brontology/graph/entity.py
> +    def get_representative_word(self) -> str:
Ich habe nochmal über den Namen nachgedacht, wir können es eigentlich direkt `__str__` nennen, das hier ist wahrscheinlich die eheste String Repräsentation, die wir nehmen

2024-03-26 20:24 UTC, fynnbrem commented on brontology/graph/entity.py
> +        # Berechnung des Zentrums der Vektoren
Die DocStrings für alle 3 Methoden müssen noch zu "echten" DocStrings umgewandelt werden (Und in englisch geschrieben werden!)

Dazu schreibt man den Text einfach in 3 Anführungszeichen statt dem Hashtag-Kommentar.
Der Unterschied zwischen Line- und Block-Kommentaren ist in Python etwas verwirrend, aber das ist er, und für DocStrings nimmt man immer Blockkommentaren.

In diesem Fall wäre das dann einfach neu:
`"""Berechnung des Zentrums der Vektoren"""` (Final in englisch natürlich)

2024-03-26 20:24 UTC, fynnbrem commented on brontology/graph/entity.py
>  class Synset:
Hier fehlt noch ein DocString für die Klasse.

2024-04-04 09:00 UTC, marvinkaldewey reviewed
Erstmal alles nachvollziehbar

2024-04-04 09:00 UTC, marvinkaldewey commented on brontology/graph/node.py
Die regelmäßigen beschreibenden Kommentare sollten wir beibehalten machen das Ganze gut verständlich 👍

2024-04-04 09:00 UTC, marvinkaldewey commented on qodana.yaml
Vlt kannst du mir einmal erklären, welches Nutzen Qodana für unser Projekt genau hat :-)

2024-04-04 09:27 UTC, merged

2024-04-04 18:09 UTC, fynnbrem commented on qodana.yaml
Qodana ist für statische Code Analyse.

Ich bin mir noch nicht ganz sicher, ob das wirklich mehr/besseren Analysen bietet als die, die PyCharm bereits built-in bietet, aber es bietet sich an, es mal zu testen.

Das hier ist nur die Konfiguration, wenn du mal PyCharm benutzt, siehst du auch was da am Ende rauskommt.

Das gehört zu meinen verzweifelten Versuchen, Python zu einer weniger katastrophalen Programmiersprache zu machen 😄