Direct object relation
fynnbrem/brontology pull request #3
Opened 2024-04-05 13:30 UTC by marvinkaldewey

Implementation of the Python function `extract_direct_object_relation`. It takes a verb and returns a `TokenRelation` object if the verb has both a direct object ("dobj") and a subject ("nsubj"). If either is missing, it returns `None`. The function uses dependency parsing to identify the subject and direct object related to the verb.

2024-04-11 00:34 UTC, fynnbrem requested changes
Funktioniert gut, das meiste hatten wir ja auch schon besprochen!

Aber unbedingt noch den `PythonNew` Ordner aus git löschen

2024-04-11 00:34 UTC, fynnbrem commented on PythonNew/pyvenv.cfg
Den Order noch löschen, venv Ordner nie auf git tun.

Der Standardordner, `.venv` wir automatisch ignoriert, wenn du da eigene Ordnernamen führst, musst du es explizit auslassen.

2024-04-18 16:43 UTC, marvinkaldewey reviewed
Done Python New gelöscht

2024-04-21 18:25 UTC, fynnbrem approved these changes

2024-04-21 18:25 UTC, merged