Text extractor
fynnbrem/brontology pull request #4
Opened 2024-04-05 13:35 UTC by marvinkaldewey

This Python script extracts text from a Wikipedia page, removes citation numbers, and writes the cleaned text to a file. It uses BeautifulSoup to parse the HTML, and the abstract base class (ABC) pattern to define a generic `Extractor` interface.

2024-04-09 03:00 UTC, fynnbrem requested changes
Habe auch nochmal getestet, funktioniert schon sehr gut! Ich freue mich, den bald zu verwenden und erste richtige Ergebnisse zu erhalten 😃

Du musst allerdings noch DocStrings für jede Klasse und Methode schreiben. Dass an jedem Parameter Type Annotations sind, finde ich schon sehr gut, aber ein kleiner DocString der die Absicht der Klasse/Methode verdeutlicht, ist notwendig,

2024-04-09 03:00 UTC, fynnbrem commented on brontology/graph/synset.py
Die Datei noch löschen da die Implementation schon woanders steckt

2024-04-09 03:00 UTC, fynnbrem commented on extracted_texts.txt
Die Datei auch löschen.
In Zukunft kannst du solche Dateien im Projekt in dem Ordner "temp" speichern. Der Ordner wird (Zumindest ab der aktuellsten master version) automatisch ignoriert.

2024-04-09 03:00 UTC, fynnbrem commented on extractor/TextExtractor.py
Entferne die Datei auch erstmal und bennen die "onepage" version um.

In Zukunft wird wahrscheinlich sowieso der rekursive Extraktor eine funktion sein, die jede Subpage findet und dann für jede Subpage wiederum einen  one-page Extraktor von dir startet.

2024-04-09 03:00 UTC, fynnbrem commented on extractor/TextExtractor_onepage.py
Dateiname: `text_extractor.py`

Außerdem muss der ganze `extractor` ordner noch in den `brontology` ordner rein.
Auf toplevel sind nur metadateien wie Projektkonfigurationen und tests

2024-04-09 03:00 UTC, fynnbrem commented on extractor/TextExtractor_onepage.py
> +class Extractor(ABC):
Schön mit der abstract class!

Die `extract`-Methode braucht allerdings noch einen return-type, damit für alle Zugriffe der  output klar ist.

Return types definierst du wie in der Implementation im `WikipediaExtractor` mit dem Pfeil `->` nach der Klammer.

2024-04-09 03:00 UTC, fynnbrem commented on extractor/TextExtractor_onepage.py
> +    def extract(self) -> List[Text]:
Der return Type ist aktuell nur ein einzelner `Text`, keine `list[Text]`

2024-04-09 03:00 UTC, fynnbrem commented on extractor/TextExtractor_onepage.py
> +        # Entfernt alle sup-Tags, die Einzelnachweise enthalten (Zahlen hinter Text)
Gut dokumentiert!

Aber dennoch, Kommentare auf englisch schreiben

2024-04-09 03:00 UTC, fynnbrem commented on extractor/TextExtractor_onepage.py
> +
Da demnächst dein Modul jetzt auch von anderen Modulen verwendet wird, eine kleine Einführung in die `main`-Klausel:

Manchmal siehst du eine Zeile mit `if __name__ == "__main__":`.
Ohne dich in technische Details zu verwickeln, hier was diese Zeile tut und warum sie notwendig ist:

Durch die Zeile wird der Code innerhalb der If-Clause __nur__ ausgeführt, wenn dieses Modul __selbst__ ausgeführt wird, aber nicht, wenn es nur von anderen modulen importiert wird.

Wenn die Klausel nicht da ist, wird jeglicher Code der hier steht, bei jedem import dieses Moduls ausgeführt, was dann in Zukunft bedeuten würde, dass, egal was man eigentlich erreichen will, bei jedem Zugriff auf dieses Modul von außen, erstmal der Python Wikipedia Artikel extrahiert wird.


Jetzt musst du entsprechend deinen ganzen Code, der nur zur Demonstration dieses Moduls da ist, genau in so eine Klausel stecken.

2024-04-18 15:51 UTC, marvinkaldewey reviewed
Kommentare eingearbeitet 💯

2024-04-18 15:51 UTC, marvinkaldewey commented on extractor/TextExtractor_onepage.py
> +    def extract(self) -> List[Text]:
Erledigt

2024-04-21 15:23 UTC, fynnbrem commented on brontology/extractor/text_extractor.py
>  with open('extracted_texts.txt', 'w', encoding='utf-8') as f:
Hier muss jetzt noch das `if __name__ == "__main__":` dran

2024-04-21 18:11 UTC, fynnbrem approved these changes

2024-04-21 18:11 UTC, fynnbrem commented on brontology/extractor/text_extractor.py
>  with open('extracted_texts.txt', 'w', encoding='utf-8') as f:
Und brauchst du diese ganze Wrapping Geschichte jetzt eigentlich überhaupt noch?
Ist zwar eine nette Exkursion gewesen, aber für unsere Anwendung ist es wohl angenehmer, wenn man sich im Editor einfach soft-wrap anmacht

2024-04-21 18:12 UTC, merged