Tests direct object relation
fynnbrem/brontology pull request #8
Opened 2024-07-17 10:19 UTC by marvinkaldewey

2024-07-17 18:44 UTC, fynnbrem requested changes
Sieht echt stark aus 💪

Die Struktur ist einheitlich und die Tests funktionieren wie sie sollen.

Eine Anmerkung habe ich noch, weil du imports noch richtig stellen muss, aber danach kann gemerged werden.

2024-07-17 18:44 UTC, fynnbrem commented on tests/brontology/relation_extraction/relation_types/test_direct_object_relation.py
> +class TokenRelation:
Bei Tests bitte nie irgendwelche Klassen oder Funktionen aus der Codebase neu definieren, hier geht es genau darum, dass jede Änderung an der Codebase direkt hier getestet werden kann.

Importiere deine Extraktionsfunktion von da, wo sie eigentlich herkommt, dann brauchst auch nicht mehr die `TokenRelation` hier.

2024-07-31 09:43 UTC, marvinkaldewey commented on tests/brontology/relation_extraction/relation_types/test_direct_object_relation.py
> +class TokenRelation:
Funktion extract_direct_object_relation und Klasse Token Relation aus der Codebase importiert.. Leider erscheint nun aus mir unerklärlichen Gründen ein ModuleNotFound Error. Vlt schauen wir da morgen einmal gemeinsam drüber.

2024-07-31 09:44 UTC, marvinkaldewey reviewed
Import Probleme Klasse und Funktion

2024-07-31 21:50 UTC, fynnbrem approved these changes

2024-07-31 21:50 UTC, merged